# Workflow to build and deploy to your GitHub Pages repo.

# Edit your project details here.
# Remember to add API_TOKEN_GITHUB in repo Settings > Secrets as well!
env:
  githubEmail: test@test.com
  deployToRepo: kickbase-information

name: Github Pages Astro CI

on:
  # Triggers the workflow on push and pull request events but only for the main branch
  push:
    branches: [main]
  # pull_request:
  #   branches: [main]
  schedule:
    - cron: "30 21 * * *" # every day at 21:30 UTC (= 22:30 CET)

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install dependencies with npm
      - name: Install dependencies
        run: npm ci

      # Build the project and add .nojekyll file to supress default behaviour
      - name: Build
        env:
          KB_EMAIL: ${{ secrets.KB_EMAIL }}
          KB_PW: ${{ secrets.KB_PW }}
          KB_LEAGUE_ID: ${{ secrets.KB_LEAGUE_ID }}
        run: |
          npm run build
          touch ./dist/.nojekyll

      # Push to your pages repo
      - name: Push to pages repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'dist'
          destination-github-username: ${{ github.actor }}
          destination-repository-name: ${{ env.deployToRepo }}
          user-email: auto@deploy.de
          user-name: auto-deploy
          commit-message: Deploy ORIGIN_COMMIT
          target-branch: gh-pages
